### ISSUE TITLE
HttpInterface with JWT token

### ISSUE THREAD

**Issue by patpatpat123** [danvega/http-interfaces#1]
Hello Dan,

Your video on https://www.youtube.com/watch?v=aR580OCEp7w is very cool, easy to understand.

Furthermore, your video regarding https://www.youtube.com/watch?v=nFKcJDpUuZ8 is also awsome.

After watching your video, I am trying to combine both.

I am trying to use spring-boot-starter-oauth2-client with the new Spring Framework release 6 HttpInterface

```
@Configuration
public class RestClientConfig {

    @Bean
    public RestClient restClient(OAuth2AuthorizedClientManager authorizedClientManager, RestClient.Builder restClientBuilder) {
        OAuth2ClientHttpRequestInterceptor interceptor = new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);
        return restClientBuilder
                .requestInterceptor(interceptor)
                .build();
    }

}
```

```
@RestController
public class LessonsController {

    private final RestClient restClient;

    public LessonsController(RestClient restClient) {
        this.restClient = restClient;
    }

    @GetMapping("/lessons")
    public String fetchLessons() {
        return restClient.get()
                .uri("https://someserver.om/someprotectedresource")
                .attributes(clientRegistrationId("my-client"))
                .retrieve()
                .body(String.class);
    }
}
```

```
spring:
  application:
    name: client-application
  security:
    oauth2:
      client:
        registration:
          my-client:
            provider: my-provider
            client-id: ididid
            client-secret: secretsecret
            authorization-grant-type: client_credentials
            scope: download
        provider:
          my-provider:
            token-uri: https://provider.com/token
```

The above is working. 
We have confirmation from the token provider we got the token, as well as from the resource server we got the resource, passing the token.
Both two steps are working fine, happy.

We now would like to do the same, with the new Spring Framework release 6 HttpInterface

When doing this:

```
@Configuration
public class UserClientConfig {

    private final RestClient restClient;

    public UserClientConfig(OAuth2AuthorizedClientManager authorizedClientManager, RestClient.Builder restClientBuilder) {
        OAuth2ClientHttpRequestInterceptor interceptor = new OAuth2ClientHttpRequestInterceptor(authorizedClientManager);
        this.restClient = restClientBuilder
                .requestInterceptor(interceptor)
                .baseUrl("https://host.com")
                .build();
    }

    @Bean
    public UserClient userClient() {
        RestClientAdapter adapter = RestClientAdapter.create(restClient);
        return HttpServiceProxyFactory.builderFor(adapter)
                .build()
                .createClient(UserClient.class);
    }

}
```

```
@HttpExchange(
        url = "/v1",
        accept = MediaType.APPLICATION_JSON_VALUE)
public interface UserClient {

    @GetExchange("/protectedresource/full")
    public User getUserById(@RequestParam Map<String, String> key value);

}
```

```
    @GetMapping("/lessons")
    public User fetchLessons() {
        return userClient.getUserById(Map.of("foo", "bar"));
    }
```

When using HttpInterface, this would not work.
The token is not fetched in the first place.
Maybe because of the lack of .attributes(clientRegistrationId("id")) for @HttpExchange @GetExchange, but not sure.

Question: how to combine Http Interface with spring-boot-starter-oauth2-client token?
